Containerfile

Currently, davincibox is building from the fedora:latest image, but this was only chosen because my other local fedora containers were using it, and not for any thoughtful reason. Switching to a fedora-toolbox image might fix #2

build: Use fedora-toolbox image

---

README.md
setup.sh
system_files/usr/bin/add-davinci-launcher
system_files/usr/bin/setup-davinci

Fixes #3 
Fixes #4 
- Implemented `add-davinci-launcher` to handle setting up .desktop files and icons, as well as their removal
- `setup-davinci` can now take a second argument to tell `add-davinci-launcher` if distrobox or toolbox are being used
- `setup.sh` passes said argument to `setup-davinci`
- README updated with new info
- Other cleanups/fixes

feat: Manually create launcher

---

README.md

It should already be obvious when distrobox and toolbox are mentioned, but it's probably for the best to clarify that this is meant for DaVinci Resolve on Linux specifically, not other platforms.

docs: Clarify that this is for Resolve on Linux

---

extra-packages

fix: Add pipewire-alsa to fix no audio on some systems

---

system_files/usr/bin/setup-davinci

Applied [MiMillieuh's fix](https://www.reddit.com/r/voidlinux/comments/12g71x0/comment/ju9ygqx/) for the error:
`/opt/resolve/bin/resolve: symbol lookup error: /usr/lib/libgdk_pixbuf-2.0.so.0: undefined symbol: g_task_set_static_name`

fix: updated gdk_pixbuf to prevent g_task_set_static_name error

---

README.md

fixed a few outdated things in the readme and convenience
the nvidia-container-runtime has been deprecated in favor of the NVIDIA container toolkit.
also added links to direct people to the github pages of Distrobox and Toolbox.

docs: Update README.md for nvidia and links

---

README.md

Consolidates the podman and distrobox/toolbox requirements, and adds information about `nvidia-container-toolkit` for NVIDIA users.
Closes #53

docs(README): Document nvidia-container-toolkit

---

Containerfile

There *shouldn't* be any regressions from making this switch, as this image was originally built on the `fedora` container image before I switched it over to uBlue's `fedora-distrobox`. The reason for the original change was because the latter was optimized for distrobox, but in hindsight I'd like to keep the image smaller for those that prefer toolbox + I want to explore using podman directly in the future instead.
Closes #55

build(Containerfile): Use upstream fedora-toolbox image as base

---

README.md

`nvidia-container-runtime` is the old package name but I mixed them up when doing #56...even though I had it correct in the PR's title...

docs(README): Use correct package name of `nvidia-container-toolkit`

---

README.md

Fixes the toolbox and distrobox commands for `setup-davinci` to use `squashfs-root` now (per #60)
Updates the disclaimers section to be a bit more accurate, now that we've had contributions for info on working GPUs and DaVinci Resolve Studio.

docs(README): Fix install instructions, update disclaimers section

---

README.md
extra-packages
system_files/usr/bin/add-davinci-launcher
system_files/usr/bin/run-davinci
system_files/usr/bin/setup-davinci

- Adds SKIP_PACKAGE_CHECK=1 during DaVinci Resolve installation, due to an error with the installer not detecting that zlib is present
- Adds mesa-libOpenCL for rusticl
- Makes rusticl opt-in with `run-davinci`

feat: Add rusticl as opt-in option

---

README.md

- Adds a section under Disclaimers to clarify that any missing codec support is most likely an upstream issue, not a davincibox issue
- Clarifies that `nvidia-container-toolkit` is to be installed on the user's host OS
- Adjusts wording in other sections

docs(README): Add section about codecs, clarify other sections

---

system_files/usr/bin/run-davinci
system_files/usr/bin/setup-davinci

- Removes the old gdk-pixbuf workaround since the required F38 package is no longer available
- Uses LD_PRELOAD to make Resolve use container's `libglib`, `libgdk_pixbuf`, `libgio`, and `libgmodule` without altering the DaVinci Resolve installation
- Refactors `run-davinci` to improve legibility
Closes #78

fix: gdk pixbuf symbol lookup error

---

system_files/usr/bin/add-davinci-launcher

- Omits the `/usr/bin/` prefix from distrobox desktop shortcuts to account for certain distrobox installation methods installing distrobox to a different path.
- Leaves toolbox path alone since that's more Fedora-specific and *should* always be at `/usr/bin/toolbox`
Fixes #80

fix(adl): Remove `/usr/bin/` prefix from distrobox shortcut

---

.github/workflows/build-davincibox.yml
README.md
setup.sh

- Makes builds daily instead of weekly
- Add a note about running `sudo dnf update` when upgrading davincibox
- Adds `sudo dnf update` steps into `setup.sh`
Closes #84 
Closes #85

fix: Ensure Fedora packages are updated during setup

---

README.md
extra-packages
system_files/usr/bin/run-davinci

- Adds `glx-utils` to allow GPU detection with `glxinfo`
- Switches to rusticl by default for AMD, but keeps ROCm as a fallback via `rocm` arg
- Keeps `rusticl` arg for Intel and Nvidia nouveau users to test
- Adds note about using `run-davinci` script when running davincibox + DaVinci Resolve in the CLI
Closes #87 
Related to #72

feat(run-davinci): Default to rusticl for AMD GPUs

---

setup.sh

- Fixes an oversight from 16b31de7a43eba6b46b65c3b4dbde7900a165bd6
- Fixes the check for whether the installer file was found valid or not
Should fix #91

fix: Use full installer path for installer extraction

---

system_files/usr/bin/run-davinci

Right now, this shouldn't actually have a big effect on things, since we're not applying any Nvidia-specific workarounds in `run-davinci` at the moment, but in the future, if we need to for e.g. laptops with Intel iGPUs + Nvidia dGPUs, we'll want to check for the Nvidia GPU first.

fix(run-davinci): Check for Nvidia GPU first

---

setup.sh

glxinfo only detects nvidia cards in hybrid GPUs laptops when executed prefixed of switcherooctl (which basically sets the env vars), or using `lshw -c video` (which lists all video devices, regardless of env vars)

fix(setup.sh): More reliable nvidia detection

---

system_files/usr/bin/add-davinci-launcher

Unlike Toolbx, distrobox-enter ignores `/etc/profile.d` files, so we have to manually source `davinci.sh` before running DaVinci Resolve and the other included programs
Closes #106

fix(adl): Manually source davinci.sh for distrobox

---

system_files/usr/bin/add-davinci-launcher

See https://github.com/zelikos/davincibox/pull/107#issuecomment-2253689350
This is cleaner than the previous solution of manually sourcing `davinci.sh` before running the respective program

refactor(adl): Use `bash -cl` to ensure a login shell for distrobox

---

extra-packages
system_files/etc/profile.d/davinci.sh
system_files/usr/bin/add-davinci-launcher
system_files/usr/bin/setup-davinci

This will remove the need of using LD_PRELOAD as of https://www.reddit.com/r/voidlinux/comments/12g71x0/comment/l2cwo27/ by forcing DaVinci Resolve binaries to use the listed libraries at the specified absolute paths:
- /usr/lib64/libglib-2.0.so.0
- /usr/lib64/libgdk_pixbuf-2.0.so.0
- /usr/lib64/libgio-2.0.so.0
- /usr/lib64/libgmodule-2.0.so.0

refactor: Utilize patchelf instead of LD_PRELOAD

---

setup.sh
system_files/etc/profile.d/davinci.sh

Changes GPU checks in `setup.sh` and `davinci.sh` to check for the driver name in use, rather than GPU vendor.
Fixes #113

fix: Check for GPU driver name, not just vendor

---

README.md

Adds to the Upgrading section that upgrades of the container *image* are only needed when davincibox's scripts are updated or prior to reporting an issue, and that `sudo dnf update` is sufficient otherwise.

docs(README): Clarify Upgrading section

---

README.md

Because just saying to "add `rocm` to the end" doesn't work anymore now that we use `/etc/profile.d/davinci.sh` for environment variables.

docs(README): Better explain ROCm opt-in for desktop shortcuts

---

extra-packages

Adds `xcb-util-cursor` to the davinci dependencies
Should fix #122

fix: Add xcb-util-cursor

---

README.md

Thanks for this project! I think it is awesome!! With this I finally got Resolve running on my Arch-Linux installation after many years :-)
I ran into some audio issues related to my Arch installation using Pulseaudio.
I added a section to the `README.md` which might help others.
Feel free to merge or propose changes.
In an ideal world the installer could detect or ask for the installed sound system and then create the `distrobox` image accordingly. But I did not have time to look into it this far. So I thought adding the info to the `README.md` is better than nothing.

docs(README): Add troubleshooting section to README

---

setup.sh

*Might* help with #140 since the error log provided mentioned a $PATH issue, but I couldn't reproduce the issue on my system so I can't verify. Even so, it's better to use the absolute path here just in case, and doesn't hurt to do so.

fix(setup.sh): Use absolute paths for internal scripts

---

system_files/usr/bin/setup-davinci

Applies the workaround described in #137. This didn't have any noticeable negative effect on my AMD system using rusticl.

fix(nvidia): Rename libDecoderOpenCL.so for companion programs

---

Containerfile

`mesa-libOpenCL` installs `OpenCL-ICD-Loader` as one of its dependencies, but the latter package conflicts with `ocl-icd`, which is a dependency of `rocm-opencl`. This removes `OpenCL-ICD-Loader` from the `davincibox-opencl` image.

fix(opencl): Remove OpenCL-ICD-Loader before installing OpenCL packages

---

system_files/etc/profile.d/davinci.sh

Sets QT_AUTO_SCREEN_SCALE_FACTOR=1 (per #159) so that Resolve will follow fractional scaling settings set by the desktop environment. Tested on GNOME, not tested on other desktops.
Fixes #150 
Fixes #152

fix: Support fractional scaling settings

---

Containerfile

Removing `OpenCL-ICD-Loader` in #158 also removed `mesa-libOpenCL`, which we still need for rusticl. This explicitly re-adds `mesa-libOpenCL` after `rocm-opencl` is installed.
Fixes #160

fix: Re-add mesa-libOpenCL in davincibox-opencl

---

Containerfile

Because `OpenCL-ICD-Loader` doesn't work on AMD GPUs. Both work fine on Intel. Untested on NVIDIA, but most people are gonna use CUDA with NVIDIA anyway
Related to #158 
Fixes #169

fix(opencl): Explicitly install `ocl-icd`

---

README.md

Extend troubleshooting section to include Resolve Studio udev rules for those using USB licence keys.

docs(README): Update README to include troubleshooting step for users of Resolve Studio with USB licence keys.

---

README.md
system_files/usr/bin/list-gpus
system_files/usr/bin/run-davinci

Adds an environment variable that is needed for switcherooctl to work in distrobox (not needed for Toolbox, but doesn't harm use in Toolbox either), as well as a `list-gpus` wrapper script for `switcherooctl list` including said environment variable.
Fixes #40 (again, for real this time hopefully)

fix: Add needed env for switcherooctl to work in distrobox

---

davinci-dependencies
system_files/usr/bin/add-davinci-launcher
system_files/usr/bin/run-davinci

Hello, very helpful project. I thought I'd fix some issues I had.
A fixed quite a few issues:
1. Binaries with spaces such as /opt/resolve/DaVinci Control Panels Setup/DaVinci Control Panels Setup would not launch.
2. Added StartupWMClass for all the .desktop files to allow GNOME to properly recognize them as apps instead of unknown apps.
3. Added some missing dependencies for Davinci Control Panels Setup
Here is a before and after for the StartupWMClass changes:
**Before:**
**After:**
The DaVinci Resolve Capture Logs app also has missing dependencies but I was unable to figure out how to fix those.

fix: binaries with spaces, added StartupWMClass, added dependencies
